const movieTitles = [
    "The Godfather",
    "The Shawshank Redemption",
    "The Dark Knight",
    "12 Angry Men",
    "Schindler's List",
    "The Lord of the Rings: The Return of the King",
    "Pulp Fiction",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Forrest Gump",
    "Fight Club",
    "Inception",
    "The Matrix",
    "Goodfellas",
    "Seven Samurai",
    "Se7en",
    "City of God",
    "The Silence of the Lambs",
    "It's a Wonderful Life",
    "Life Is Beautiful",
    "Saving Private Ryan",
    "Interstellar",
    "The Green Mile",
    "Star Wars: Episode IV - A New Hope",
    "Terminator 2: Judgment Day",
    "Back to the Future",
    "Spirited Away",
    "Psycho",
    "The Pianist",
    "Parasite",
    "Gladiator",
    "The Lion King",
    "Whiplash",
    "The Departed",
    "The Prestige",
    "Casablanca",
    "Once Upon a Time in the West",
    "Rear Window",
    "Cinema Paradiso",
    "Alien",
    "Modern Times",
    "The Shining",
    "Django Unchained",
    "Princess Mononoke",
    "Raiders of the Lost Ark",
    "The Lives of Others",
    "Grave of the Fireflies",
    "Memento",
    "The Great Dictator",
    "The Intouchables",
    "Apocalypse Now",
    "Indiana Jones and the Last Crusade",
    "Die Hard",
    "The Usual Suspects",
    "The Sting",
    "A Beautiful Mind",
    "Amadeus",
    "Good Will Hunting",
    "The Sixth Sense",
    "Jurassic Park",
    "The Truman Show",
    "Groundhog Day",
    "Blade Runner",
    "Finding Nemo",
    "The Big Lebowski",
    "No Country for Old Men",
    "Kill Bill: Vol. 1",
    "Mary and Max",
    "How to Train Your Dragon",
    "Gone with the Wind",
    "Into the Wild",
    "There Will Be Blood",
    "Life of Brian"
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = movieTitles;
}
