[build]
  command = "npm run build"
  publish = "."
  functions = "api"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "cheerio"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
